Разметка всех страниц
htmlacademy-adaptive/2097425-cat-energy-26 pull request #2
Opened 2022-07-30 09:59 UTC by sashadudkina5

Пока что не стала делать интерактивную карту в футере. Увидела, что Андрей в Дискорде написал под одним из вопросов, что будем разбирать реализацию карты далее по ходу курса. Но если уже сейчас необходимо сделать, то попробую разобраться)

2022-07-31 08:31 UTC, babtshe requested changes

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +  <link rel="icon" type="image/png" sizes="32x32" href="../images/favicon.png">
Хорошо бы использовать путь относительно папки с проектом, это позволит избежать такого:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/30229773/182015609-c95d18f0-698a-4fa8-8345-97159aeb0865.png">

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +    <a class="main-header__logo logo-image" href="#">
страница не должна ссылаться сама на себя, `href` на главной можно убрать из логотипа.

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +            <a class="site-list__link" href="#">
❗️

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +      <div class="main-section__wrapper">
нет смысла добавлять обёртки до тех пор, пока он них нет практической пользы. Добавить при стилизации проще, чем удалить потом.

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +        <a class="main-section__link-to-catalog choose-program" href="form.html">Подобрать программу</a>
Лучше избегать привязки названия класса к содержимому блока. После сдачи сайта текст содержимого может сто раз поменяться, и класс будет вводить в заблуждение.

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +              <a class="programs__link-to-catalog" href="catalog.html">каталог slim</a>
❗️

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +              <h3 class="programs__title">Набор массы</h3>
Обрати внимание на структуру и иерархию заголовков.

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +        <h5 class="example__title">Живой пример</h5>
❗️

2022-07-31 08:31 UTC, babtshe commented on source/index.html
> +            <h6 class="invitation__title">приглашаем к сотрудничеству дилеров!</h6>
❗️

2022-07-31 08:31 UTC, babtshe commented on source/catalog.html
> +            <a class="site-list__link" href="#">
❗️

2022-07-31 08:31 UTC, babtshe commented on source/catalog.html
> +          <li class="catalog__item product catalog__item--chicken-500">
товаров могут быть сотни тысяч, точно не стоит делать отдельный модификатор под каждый товар.

2022-07-31 08:31 UTC, babtshe commented on source/catalog.html
> +            <button class="product__purchase button" type="button">заказать</button>
лучше использовать ссылку вместо кнопки. В этом случае у пользователя останется возможность заказать товар, даже если скрипты по какой-то причине будут недоступны.

2022-07-31 08:31 UTC, babtshe commented on source/catalog.html
> +        </div>
Хорошо бы добавить ссылку

2022-07-31 08:31 UTC, babtshe commented on source/form.html
> +            <input class="basic__input" type="text" placeholder="" value="Барсик" name="name" id="name" required>
Не стоит путать подсказку с предзаполненным значением. Если кота зовут Васька, пользователю придётся удалять то, что уже есть форме, а это не ок.

2022-07-31 08:31 UTC, babtshe commented on source/form.html
> +        </fieldset>
для переключателей `radio` или `checkbox` в группе полезно использовать одно имя, но разные значения, это сильно упрощает беку работу с данными, так как результат приходит в виде аккуратного массива.

2022-07-31 08:31 UTC, babtshe commented on source/form.html
> +        <button class="questionnaire__button button" type="button">отправить заявку</button>
для отправки формы у кнопки есть специальный тип

2022-08-03 05:56 UTC, babtshe requested changes

2022-08-03 05:56 UTC, babtshe commented on source/form.html
> +            <input class="additional__input" type="checkbox" id="water" name="additional-product" vaqlue="water">
❗️

2022-08-03 05:56 UTC, babtshe commented on source/index.html
> +              <h3 class="programs__title">Похудение</h3>
с заголовками всё ещё беда здесь и далее по коду, хорошо бы доку глянуть: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

2022-08-03 05:56 UTC, babtshe commented on source/catalog.html
> +            <img class="product__image" src="/images/chiken-500.png" width="68" height="86"
ссылки пока не побеждены:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/30229773/182533910-b7de5409-55fd-4bd7-a513-75fdcc9609e0.png">
Можно либо доку почитать, либо прям в собранной версии поэкспериментировать:
https://htmlacademy-adaptive.github.io/2097425-cat-energy-26/2/catalog.html

2022-08-03 05:56 UTC, babtshe commented on source/form.html
>          </fieldset>
Предзаполненное значение в поле комментария тоже было бы правильно убрать

2022-08-03 14:09 UTC, sashadudkina5 commented on source/index.html
> +              <h3 class="programs__title">Похудение</h3>
поправила заголовки далее по коду после секции с выбором программы

2022-08-03 15:12 UTC, sashadudkina5 commented on source/catalog.html
> +            <img class="product__image" src="/images/chiken-500.png" width="68" height="86"
Попробовала src=**"images**/chiken-500.png" кажется, что это должно быть относительно папки с проектом,

но я не понимаю , как можно проверить, не будет ли опять ошибка, пыталась разобраться, но что-то не получается

2022-08-03 15:13 UTC, sashadudkina5 commented on source/index.html
> +              <h3 class="programs__title">Похудение</h3>
а какая конкретно беда в секции с выбором программы - не понимаю( конкретно здесь мне кажется все правильным
подскажете, пожалуйста?

2022-08-04 05:50 UTC, babtshe commented on source/index.html
> +              <h3 class="programs__title">Похудение</h3>
Важно не пропускать уровни заголовков. Не может быть h1>h3, должно быть h1>h2>h3 итд. Если оставить только заголовки на странице, должно получиться осмысленное содержание с однородными элементами на одном уровне и подразделами уровнями ниже. Заголовки используются именно для выстраивания смысловой структуры, а не стилизации.

2022-08-04 05:51 UTC, babtshe commented on source/catalog.html
> +            <img class="product__image" src="/images/chiken-500.png" width="68" height="86"
Можно тыкать на кнопочку публикации в интерфейсе академии:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/30229773/182772626-96124ca6-8643-4c0a-a359-73ed870344c4.png">
и по ссылке на собранную версию смотреть как будет выглядеть сайт у гипотетического заказчика.

2022-08-04 05:52 UTC, babtshe approved these changes

2022-08-04 05:52 UTC, merged

2022-08-05 12:09 UTC, sashadudkina5 commented on source/catalog.html
> +            <img class="product__image" src="/images/chiken-500.png" width="68" height="86"
спасибо!

2022-08-05 12:10 UTC, sashadudkina5 commented on source/index.html
> +              <h3 class="programs__title">Похудение</h3>
спасибо!